### ISSUE TITLE
Migrate to official webview

### ISSUE THREAD

**Issue by Mohsen7s** [ZeroNetX/zeronet_mobile#12]
Is migration to official webview_flutter on the roadmap ? Any ETA ?
Currently used flutter_webview_plugin have security issues which can lead to leak real IP of visitors.

**Comment by canewsin** [comment]
> Is migration to official webview_flutter on the roadmap ? Any ETA ? Currently used flutter_webview_plugin have security issues which can lead to leak real IP of visitors.

Oh, didn't know about security issues. will add to my list, PR's are always welcomed, if you can contribute.

**Comment by canewsin** [comment]
flutter_webview_plugin is replaced inapp_webview plugin, it features turning off external network access thus prevents up leakage.
