### ISSUE TITLE
No toolbar icons

### ISSUE THREAD

**Issue by MikronT** [ZeroNetX/zeronet_mobile#20]
Toolbar icons just disappeared. Both Main and Settings activities are affected

![image](https://user-images.githubusercontent.com/45333177/168490539-d203aa90-3f36-4071-8b8c-df01a58ddfee.png)

**Comment by canewsin** [comment]
Thanks for reporting, just noticed that, already fixed awaiting code push. What about browsing ZeroNet sites within the App ? Are you facing net::ERR_CACHE_MISS error as reported by someone on ThreadIt ?

**Comment by canewsin** [comment]
Fixed in https://github.com/ZeroNetX/zeronet_mobile/commit/ce8a492919bb0fb0f8bdd6c4897afac88f1f16c3
