### ISSUE TITLE
net::ERR_CACHE_MISS when Internet Access in Browser is disabled

### ISSUE THREAD

**Issue by MikronT** [ZeroNetX/zeronet_mobile#21]
When **Internet Access in Browser** is denied, I always receive the `net::ERR_CACHE_MISS` error

![Screenshot_2022-05-16-09-34-05-447_in canews zeronetmobile](https://user-images.githubusercontent.com/45333177/168532990-f1eaeb08-e35e-448e-8ed6-1a1bc3b4cd62.jpg)

My settings

- Plugins - Default
- Additional BitTorrent Trackers - Enabled by default
- Enable ZeroNet Filters - Enabled by default
- Public DataFolder - Disabled
- Internet Access in Browser - Disabled
- The rest are set to defaults

P.S. Forgot to submit this issue yesterday

**Comment by canewsin** [comment]
Fixed in https://github.com/ZeroNetX/zeronet_mobile/commit/ce8a492919bb0fb0f8bdd6c4897afac88f1f16c3
