### ISSUE TITLE
Wrong toolbar theme on 1st launch of the browser

### ISSUE THREAD

**Issue by MikronT** [ZeroNetX/zeronet_mobile#22]
Every time I launch ZeroNet and open any of the zites suggested for the 1st time, I see the bottom toolbar being white, regardless of the theme selected in the settings

![Screenshot_2022-05-16-09-52-08-003_in canews zeronetmobile](https://user-images.githubusercontent.com/45333177/168536948-143bd945-f372-42e7-bce8-c39a32e3ff91.jpg)

But if I just go back and open a zite again, it's colored right

![Screenshot_2022-05-16-09-52-13-777_in canews zeronetmobile](https://user-images.githubusercontent.com/45333177/168536970-1d0ce09c-f6e0-4b97-b81e-7c76f62ddd4e.jpg)

**Comment by MikronT** [comment]
Some context I forgot to mention

- Android 10 (MIUI 12.5.3)
- Dark theme enabled systemwide
- Latest beta of ZeroNetX

**Comment by canewsin** [comment]
Fixed in referenced commit.
