### ISSUE TITLE
stuck at downloading

### ISSUE THREAD

**Issue by nerd36** [ZeroNetX/zeronet_mobile#28]
stuck at downloading. you can see network traffic above screen shot. connection speed is 1mb/s
![Screenshot_20220925-142509](https://user-images.githubusercontent.com/89322511/192140889-c91de373-699c-4fb4-942c-a699bf3a5abf.png)

ver: 0.8.7
Generally speaking there is nothing to show user if there is a problem. e.g. a download bar, traffic speed, showing errors

**Comment by canewsin** [comment]
@nerd36 Try https://github.com/ZeroNetX/zeronet_mobile/releases/latest, Fixed binary download Issues.
